name: "Get Repository Branch and Commit"
description: >-
  Determines the current branch name and commit SHA (full hash) of the Git
  repository located at the specified directory. Exports the values as
  configurable environment variables if the corresponding variable names
  are provided.
inputs:
  repo-dir:
    description: "The path to the repository directory (relative to the workspace)."
    required: true
  branch-var:
    description: "The name of the environment variable to set with the current branch name (optional)."
    required: false
  commit-var:
    description: "The name of the environment variable to set with the full commit SHA (optional)."
    required: false
runs:
  using: "composite"
  steps:
    - name: Get branch and commit from repository
      shell: bash
      run: |
        repo_dir="${{ inputs.repo-dir }}"

        # Validate repository directory
        if [[ ! -d "$repo_dir" ]]; then
          echo "Error: Specified repository directory '$repo_dir' does not exist."
          exit 1
        fi

        if ! git -C "$repo_dir" rev-parse --git-dir >/dev/null 2>&1; then
          echo "Error: '$repo_dir' is not a valid Git repository."
          exit 1
        fi

        # Get current branch name (or "detached" if in detached HEAD state)
        branch=$(git -C "$repo_dir" rev-parse --abbrev-ref HEAD)
        if [[ "$branch" == "HEAD" ]]; then
          branch="detached"
        fi

        # Get full commit SHA
        commit=$(git -C "$repo_dir" rev-parse HEAD)

        # Set branch variable if name is provided
        if [[ -n "${{ inputs.branch-var }}" ]]; then
          echo "${{ inputs.branch-var }}=$branch"
          echo "${{ inputs.branch-var }}=$branch" >> "$GITHUB_ENV"
        fi

        # Set commit variable if name is provided
        if [[ -n "${{ inputs.commit-var }}" ]]; then
          echo "${{ inputs.commit-var }}=$commit"
          echo "${{ inputs.commit-var }}=$commit" >> "$GITHUB_ENV"
        fi
