name: "Set Release and Package Tags"
description: >-
  Generates a daily release tag in YYYY-MM-DD format (e.g., "2025-12-22")
  and a corresponding package tag with dashes removed (e.g., "20251222").
  Exports both as environment variables and action outputs for subsequent steps.
outputs:
  release-tag:
    description: "The generated release tag (YYYY-MM-DD format)"
    value: ${{ steps.determine-tags.outputs.release-tag }}
  package-tag:
    description: "The generated package tag (YYYYMMDD format)"
    value: ${{ steps.determine-tags.outputs.package-tag }}
runs:
  using: "composite"
  steps:
    - name: Set release and package tags
      id: determine-tags
      shell: bash
      run: |
        release_tag="$(date +'%Y-%m-%d')"
        package_tag="${release_tag//-/}"

        echo "RELEASE_TAG=$release_tag"
        echo "PACKAGE_TAG=$package_tag"

        echo "release-tag=$release_tag" >> $GITHUB_OUTPUT
        echo "package-tag=$package_tag" >> $GITHUB_OUTPUT

        # Export to GITHUB_ENV for backward compatibility with inline steps
        echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV
        echo "PACKAGE_TAG=$package_tag" >> $GITHUB_ENV

