name: "Check Platform"
description: >-
  Verifies that the workflow is running on the specified operating system
  and architecture (case-insensitive comparison). Fails the workflow with
  a clear error message if the conditions are not met.
inputs:
  os:
    description: "The required operating system (e.g., 'Darwin' for macOS, 'Linux' for Linux)."
    required: true
  arch:
    description: "The required architecture (e.g., 'arm64', 'x86_64')."
    required: true
runs:
  using: "composite"
  steps:
    - name: Check operating system and architecture
      shell: bash
      run: |
        # For cross platform debugging.
        set -x
        uname || true
        uname -o || true
        uname -s || true
        uname -n || true
        uname -p || true
        uname -r || true
        uname -v || true

        required_os="${{ inputs.os }}"
        required_arch="${{ inputs.arch }}"

        detected_os="$(uname)"
        detected_arch="$(uname -m)"

        # Convert to lowercase using portable tr
        detected_os_lower=$(echo "$detected_os" | tr '[:upper:]' '[:lower:]')
        required_os_lower=$(echo "$required_os" | tr '[:upper:]' '[:lower:]')
        detected_arch_lower=$(echo "$detected_arch" | tr '[:upper:]' '[:lower:]')
        required_arch_lower=$(echo "$required_arch" | tr '[:upper:]' '[:lower:]')

        echo "Detected OS: $detected_os"
        echo "Detected architecture: $detected_arch"
        echo "Required OS: $required_os"
        echo "Required architecture: $required_arch"

        # Case-insensitive comparison
        if [[ "$detected_os_lower" != "$required_os_lower" || "$detected_arch_lower" != "$required_arch_lower" ]]; then
          echo "Error: This workflow requires OS='$required_os_lower' and architecture='$required_arch_lower'."
          echo "Current: OS='$detected_os_lower', Architecture='$detected_arch_lower'"
          exit 1
        fi

        echo "Platform check passed: $detected_os $detected_arch"